/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/communities/{id}/voice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["VoiceStateDto"];
                        "application/json": components["schemas"]["VoiceStateDto"];
                        "text/json": components["schemas"]["VoiceStateDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/communities/{id}/voice/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["JoinVoiceRequest"];
                    "text/json": components["schemas"]["JoinVoiceRequest"];
                    "application/*+json": components["schemas"]["JoinVoiceRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["VoiceJoinDto"];
                        "application/json": components["schemas"]["VoiceJoinDto"];
                        "text/json": components["schemas"]["VoiceJoinDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/communities/{id}/voice/leave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VoiceLeaseRequest"];
                    "text/json": components["schemas"]["VoiceLeaseRequest"];
                    "application/*+json": components["schemas"]["VoiceLeaseRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["VoiceStateDto"];
                        "application/json": components["schemas"]["VoiceStateDto"];
                        "text/json": components["schemas"]["VoiceStateDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/communities/{id}/voice/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VoiceLeaseRequest"];
                    "text/json": components["schemas"]["VoiceLeaseRequest"];
                    "application/*+json": components["schemas"]["VoiceLeaseRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": boolean;
                        "application/json": boolean;
                        "text/json": boolean;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/communities/{id}/voice/disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VoiceLeaseRequest"];
                    "text/json": components["schemas"]["VoiceLeaseRequest"];
                    "application/*+json": components["schemas"]["VoiceLeaseRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": boolean;
                        "application/json": boolean;
                        "text/json": boolean;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/voice/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/communities/{community}/channels/{channel}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    before?: string;
                };
                header?: never;
                path: {
                    community: string;
                    channel: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageSnapshot"];
                        "application/json": components["schemas"]["MessageSnapshot"];
                        "text/json": components["schemas"]["MessageSnapshot"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    community: string;
                    channel: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SendMessageRequest"];
                    "text/json": components["schemas"]["SendMessageRequest"];
                    "application/*+json": components["schemas"]["SendMessageRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageDto"];
                        "application/json": components["schemas"]["MessageDto"];
                        "text/json": components["schemas"]["MessageDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/communities/{community}/channels/{channel}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    after?: string;
                };
                header?: never;
                path: {
                    community: string;
                    channel: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CatchUpPage"];
                        "application/json": components["schemas"]["CatchUpPage"];
                        "text/json": components["schemas"]["CatchUpPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/communities/{community}/channels/{channel}/messages/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    community: string;
                    channel: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EditMessageRequest"];
                    "text/json": components["schemas"]["EditMessageRequest"];
                    "application/*+json": components["schemas"]["EditMessageRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCommandResult"];
                        "application/json": components["schemas"]["MessageCommandResult"];
                        "text/json": components["schemas"]["MessageCommandResult"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/communities/{community}/channels/{channel}/messages/{id}/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    community: string;
                    channel: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DeleteMessageRequest"];
                    "text/json": components["schemas"]["DeleteMessageRequest"];
                    "application/*+json": components["schemas"]["DeleteMessageRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCommandResult"];
                        "application/json": components["schemas"]["MessageCommandResult"];
                        "text/json": components["schemas"]["MessageCommandResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LivenessResponse"];
                        "application/json": components["schemas"]["LivenessResponse"];
                        "text/json": components["schemas"]["LivenessResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ReadinessResponse"];
                        "application/json": components["schemas"]["ReadinessResponse"];
                        "text/json": components["schemas"]["ReadinessResponse"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ReadinessResponse"];
                        "application/json": components["schemas"]["ReadinessResponse"];
                        "text/json": components["schemas"]["ReadinessResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FoundationInfo"];
                        "application/json": components["schemas"]["FoundationInfo"];
                        "text/json": components["schemas"]["FoundationInfo"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/communities/{id}/access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AccessPolicy"];
                        "application/json": components["schemas"]["AccessPolicy"];
                        "text/json": components["schemas"]["AccessPolicy"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SaveAccessRequest"];
                    "text/json": components["schemas"]["SaveAccessRequest"];
                    "application/*+json": components["schemas"]["SaveAccessRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AccessSaved"];
                        "application/json": components["schemas"]["AccessSaved"];
                        "text/json": components["schemas"]["AccessSaved"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/communities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CommunitySummary"][];
                        "application/json": components["schemas"]["CommunitySummary"][];
                        "text/json": components["schemas"]["CommunitySummary"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateCommunityRequest"];
                    "text/json": components["schemas"]["CreateCommunityRequest"];
                    "application/*+json": components["schemas"]["CreateCommunityRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CommunityDetails"];
                        "application/json": components["schemas"]["CommunityDetails"];
                        "text/json": components["schemas"]["CommunityDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/communities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CommunityDetails"];
                        "application/json": components["schemas"]["CommunityDetails"];
                        "text/json": components["schemas"]["CommunityDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/communities/{id}/channels/{channelId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    channelId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ChannelSummary"];
                        "application/json": components["schemas"]["ChannelSummary"];
                        "text/json": components["schemas"]["ChannelSummary"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/communities/{id}/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["InviteSummary"][];
                        "application/json": components["schemas"]["InviteSummary"][];
                        "text/json": components["schemas"]["InviteSummary"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateInviteRequest"];
                    "text/json": components["schemas"]["CreateInviteRequest"];
                    "application/*+json": components["schemas"]["CreateInviteRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreatedInvite"];
                        "application/json": components["schemas"]["CreatedInvite"];
                        "text/json": components["schemas"]["CreatedInvite"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/communities/{id}/invites/{inviteId}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    inviteId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["InviteSummary"];
                        "application/json": components["schemas"]["InviteSummary"];
                        "text/json": components["schemas"]["InviteSummary"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/communities/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AcceptInviteRequest"];
                    "text/json": components["schemas"]["AcceptInviteRequest"];
                    "application/*+json": components["schemas"]["AcceptInviteRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CommunityDetails"];
                        "application/json": components["schemas"]["CommunityDetails"];
                        "text/json": components["schemas"]["CommunityDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/communities/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MemberSummary"][];
                        "application/json": components["schemas"]["MemberSummary"][];
                        "text/json": components["schemas"]["MemberSummary"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/communities/{id}/members/{memberId}/ban": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    memberId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BanMemberRequest"];
                    "text/json": components["schemas"]["BanMemberRequest"];
                    "application/*+json": components["schemas"]["BanMemberRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MemberSummary"];
                        "application/json": components["schemas"]["MemberSummary"];
                        "text/json": components["schemas"]["MemberSummary"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/communities/{id}/members/{memberId}/kick": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    memberId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": boolean;
                        "application/json": boolean;
                        "text/json": boolean;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/communities/{id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuditDto"][];
                        "application/json": components["schemas"]["AuditDto"][];
                        "text/json": components["schemas"]["AuditDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/communities/{id}/leave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": boolean;
                        "application/json": boolean;
                        "text/json": boolean;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CsrfResponse"];
                        "application/json": components["schemas"]["CsrfResponse"];
                        "text/json": components["schemas"]["CsrfResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                    "text/json": components["schemas"]["RegisterRequest"];
                    "application/*+json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserProfile"];
                        "application/json": components["schemas"]["UserProfile"];
                        "text/json": components["schemas"]["UserProfile"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserProfile"];
                        "application/json": components["schemas"]["UserProfile"];
                        "text/json": components["schemas"]["UserProfile"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserProfile"];
                        "application/json": components["schemas"]["UserProfile"];
                        "text/json": components["schemas"]["UserProfile"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateProfileRequest"];
                    "text/json": components["schemas"]["UpdateProfileRequest"];
                    "application/*+json": components["schemas"]["UpdateProfileRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserProfile"];
                        "application/json": components["schemas"]["UserProfile"];
                        "text/json": components["schemas"]["UserProfile"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AcceptInviteRequest: {
            code: string;
        };
        AccessPolicy: {
            version: string;
            roles: components["schemas"]["RolePolicy"][];
            categories: components["schemas"]["CategoryPolicy"][];
            channels: components["schemas"]["ChannelPolicy"][];
            members: components["schemas"]["MemberRolePolicy"][];
            categoryRules: components["schemas"]["ResourceRule"][];
            channelRules: components["schemas"]["ResourceRule"][];
            /** Format: uuid */
            voiceCategoryId?: null | string;
            voiceRules?: null | components["schemas"]["ResourceRule"][];
        };
        AccessSaved: {
            version: string;
            appliedVersion: string;
        };
        AuditDto: {
            id: string;
            actorName: string;
            action: string;
            targetId: string;
            /** Format: date-time */
            createdAt: string;
        };
        BanMemberRequest: {
            banned: boolean;
        };
        CatchUpPage: {
            events: components["schemas"]["MessageEvent"][];
            nextSequence: string;
            watermark: string;
            hasMore: boolean;
        };
        CategoryPolicy: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        ChannelPolicy: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uuid */
            categoryId: null | string;
        };
        ChannelSummary: {
            id: string;
            name: string;
            categoryName?: null | string;
            /** @default true */
            canSend: boolean;
            sendDeniedBy?: null | string;
            /** @default false */
            canManageMessages: boolean;
        };
        CommunityDetails: {
            id: string;
            name: string;
            ownerId: string;
            role: string;
            /** Format: int32 */
            memberCount: number | string;
            channels: components["schemas"]["ChannelSummary"][];
            /**
             * Format: int32
             * @default 0
             */
            permissions: number | string;
            /**
             * Format: int32
             * @default 0
             */
            rank: number | string;
            /** @default true */
            canViewVoice: boolean;
        };
        CommunitySummary: {
            id: string;
            name: string;
            role: string;
        };
        CreateCommunityRequest: {
            /** Format: uuid */
            clientRequestId: string;
            name: string;
        };
        CreatedInvite: {
            invite: components["schemas"]["InviteSummary"];
            code: string;
        };
        CreateInviteRequest: {
            /** Format: uuid */
            clientRequestId: string;
            /** Format: int32 */
            lifetimeHours: number | string;
            /** Format: int32 */
            maxUses: number | string;
        };
        CsrfResponse: {
            requestToken: string;
        };
        DeleteMessageRequest: {
            /** Format: uuid */
            clientRequestId: string;
            expectedVersion: string;
        };
        EditMessageRequest: {
            /** Format: uuid */
            clientRequestId: string;
            expectedVersion: string;
            content: string;
        };
        FoundationInfo: {
            product: string;
            milestone: string;
        };
        InviteSummary: {
            id: string;
            /** Format: int32 */
            maxUses: number | string;
            /** Format: int32 */
            uses: number | string;
            /** Format: date-time */
            expiresAt: string;
            revoked: boolean;
        };
        JoinVoiceRequest: {
            /** Format: uuid */
            clientRequestId: string;
        };
        LivenessResponse: {
            status: string;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        MemberRolePolicy: {
            /** Format: uuid */
            userId: string;
            roleIds: string[];
        };
        MemberSummary: {
            userId: string;
            displayName: string;
            status: string;
            isOwner: boolean;
            /**
             * Format: int32
             * @default 0
             */
            rank: number | string;
        };
        MessageCommandResult: {
            messageId: string;
            appliedVersion: string;
            current: components["schemas"]["MessageDto"];
        };
        MessageDto: {
            id: string;
            channelId: string;
            authorId: string;
            authorName: string;
            clientMessageId: string;
            sequence: string;
            content: string;
            /** Format: date-time */
            createdAt: string;
            /** @default 1 */
            version: string;
            /** Format: date-time */
            updatedAt?: null | string;
            /** @default false */
            deleted: boolean;
        };
        MessageEvent: {
            eventId: string;
            channelId: string;
            sequence: string;
            kind: string;
            /** Format: int32 */
            schemaVersion: number | string;
            payload: null | components["schemas"]["MessageDto"];
            /** @default  */
            messageId: string;
            /** @default 1 */
            version: string;
        };
        MessageSnapshot: {
            messages: components["schemas"]["MessageDto"][];
            watermark: string;
            hasOlder: boolean;
        };
        ReadinessResponse: {
            status: string;
            checks: {
                [key: string]: string;
            };
        };
        RegisterRequest: {
            email: string;
            password: string;
            displayName: string;
        };
        ResourceRule: {
            /** Format: uuid */
            resourceId: string;
            /** Format: uuid */
            roleId: string;
            /** Format: int32 */
            allow: number | string;
            /** Format: int32 */
            deny: number | string;
        };
        RolePolicy: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: int32 */
            grants: number | string;
            /**
             * Format: int32
             * @default 1
             */
            rank: number | string;
        };
        SaveAccessRequest: {
            /** Format: uuid */
            clientRequestId: string;
            policy: components["schemas"]["AccessPolicy"];
        };
        SendMessageRequest: {
            /** Format: uuid */
            clientMessageId: string;
            content: string;
        };
        UpdateProfileRequest: {
            displayName: string;
        };
        UserProfile: {
            id: string;
            email: string;
            displayName: string;
        };
        VoiceJoinDto: {
            leaseId: string;
            identity: string;
            generation: string;
            url: string;
            token: string;
            /** Format: date-time */
            expiresAt: string;
            /** @default true */
            canSpeak: boolean;
        };
        VoiceLeaseRequest: {
            /** Format: uuid */
            leaseId: string;
        };
        VoiceMemberDto: {
            identity: string;
            displayName: string;
            speakingAllowed: boolean;
            /** Format: int32 */
            audioTracks: number | string;
        };
        VoiceStateDto: {
            status: string;
            generation: string;
            operationId: null | string;
            /** Format: date-time */
            completedAt: null | string;
            controlUnavailable: boolean;
            myLeaseId: null | string;
            participants: components["schemas"]["VoiceMemberDto"][];
            /** @default true */
            canConnect: boolean;
            /** @default true */
            canSpeak: boolean;
            /** @default false */
            canModerate: boolean;
            deniedBy?: null | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
